import { Researcher, Publication } from '../types';

export const SEED_RESEARCHERS: Researcher[] = [
  {
    id: 'res-sarah-adeyemi',
    fullName: 'Dr. Sarah Adeyemi',
    profilePhoto: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=300&h=300',
    role: 'Senior Researcher',
    institution: 'University of Lagos',
    country: 'Nigeria',
    bio: 'Dr. Sarah Adeyemi is an environmental scientist specializing in organic waste valorization and solar PV integrations in tropical microgrids. Her research bridges the gap between biochemical feedstock analysis and rural solar hybrid deployment. She has led numerous municipal solid waste audits in Southwest Nigeria and works closely with clean-energy policy advisors across West Africa.',
    researchInterests: ['Solar Energy', 'Waste-to-Energy', 'Energy Policy', 'Sustainable Development'],
    verified: true,
    followers: ['sandbox-chidi-okafor'],
    following: 142,
    publicationCount: 34,
    downloads: 1420,
    views: 4890,
    citations: 620,
    createdAt: '2025-01-10T12:00:00Z',
    orcid: '0000-0002-1823-4412',
    googleScholar: 'https://scholar.google.com/citations?user=sarah_adeyemi_nexus',
    linkedin: 'https://linkedin.com/in/sarah-adeyemi-nexus',
    email: 'sarah.adeyemi@unilag.edu.ng',
    website: 'https://unilag.edu.ng/staff/sarah-adeyemi',
    qualifications: ['Ph.D. in Chemical & Process Engineering (University of Lagos)', 'M.Sc. in Renewable Energy Systems (KTH Royal Institute of Technology)'],
    experienceYears: 12
  },
  {
    id: 'res-amadi-keita',
    fullName: 'Prof. Amadi Keita',
    profilePhoto: 'https://images.unsplash.com/photo-1531427186611-ecfd6d936c79?auto=format&fit=crop&q=80&w=300&h=300',
    role: 'Lecturer / Professor',
    institution: 'Université Cheikh Anta Diop',
    country: 'Senegal',
    bio: 'Prof. Amadi Keita has over twenty years of research and teaching experience in thermochemical biomass conversion. He spearheads the Senegal Aurenix Research Initiative, focusing on agricultural residues such as peanut hulls and rice husks for gasification. His work provides decentralized power solutions to dozens of off-grid agricultural cooperatives in rural Senegal.',
    researchInterests: ['Bioenergy', 'Circular Economy', 'Sustainable Development', 'Rural Electrification'],
    verified: true,
    followers: [],
    following: 98,
    publicationCount: 52,
    downloads: 2890,
    views: 8900,
    citations: 1450,
    createdAt: '2024-05-15T09:30:00Z',
    orcid: '0000-0001-9082-1256',
    googleScholar: 'https://scholar.google.com/citations?user=amadi_keita_nexus',
    linkedin: 'https://linkedin.com/in/amadi-keita-nexus',
    email: 'amadi.keita@ucad.edu.sn',
    website: 'https://ucad.sn/faculty/amadi-keita',
    qualifications: ['Ph.D. in Mechanical Engineering (Université de Sherbrooke)', 'M.Sc. in Thermodynamics (UCAD)'],
    experienceYears: 22
  },
  {
    id: 'res-almaz-demissie',
    fullName: 'Almaz Demissie',
    profilePhoto: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=300&h=300',
    role: 'Student',
    institution: 'Addis Ababa University',
    country: 'Ethiopia',
    bio: 'Almaz Demissie is a doctoral candidate at Addis Ababa University. Her research targets the simulation and optimization of run-of-river small hydropower facilities in mountainous regions of East Africa. She is enthusiastic about integrating hydrological models with climate change projections to design resilient local grid infrastructure.',
    researchInterests: ['Hydropower', 'Climate Change', 'Energy Storage', 'Smart Grids'],
    verified: false,
    followers: ['res-sarah-adeyemi'],
    following: 45,
    publicationCount: 8,
    downloads: 310,
    views: 1250,
    citations: 18,
    createdAt: '2025-11-02T14:45:00Z',
    linkedin: 'https://linkedin.com/in/almaz-demissie-nexus',
    email: 'almaz.demissie@aau.edu.et',
    qualifications: ['M.Sc. in Civil & Environmental Engineering (Addis Ababa University)', 'B.Sc. in Hydraulics (AAU)'],
    experienceYears: 4
  },
  {
    id: 'res-chinedu-okafor',
    fullName: 'Engr. Chinedu Okafor',
    profilePhoto: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=300&h=300',
    role: 'Industry Professional',
    institution: 'Africa CleanTech Solutions',
    country: 'Kenya',
    bio: 'Engr. Chinedu Okafor is a microgrid design specialist based in Nairobi. With more than a decade in the energy sector, he focuses on smart grid controls, commercial battery chemistry, and high-yield solar arrays. He is passionate about scaling mini-grids to power productive agricultural use cases such as cold-storage chains across the East African Rift.',
    researchInterests: ['Smart Grids', 'Energy Storage', 'Solar Energy', 'Rural Electrification'],
    verified: true,
    followers: [],
    following: 110,
    publicationCount: 15,
    downloads: 720,
    views: 3100,
    citations: 180,
    createdAt: '2025-03-20T08:15:00Z',
    linkedin: 'https://linkedin.com/in/chinedu-okafor-cleantech',
    email: 'chinedu.okafor@cleantech-solutions.co.ke',
    website: 'https://cleantech-solutions.co.ke/team/chinedu',
    qualifications: ['M.Eng. in Electrical Power Systems (University of Nairobi)', 'Certified Energy Manager (Association of Energy Engineers)'],
    experienceYears: 11
  },
  {
    id: 'res-miriam-kawira',
    fullName: 'Dr. Miriam Kawira',
    profilePhoto: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&q=80&w=300&h=300',
    role: 'Researcher',
    institution: 'Nelson Mandela African Institution of Science',
    country: 'Tanzania',
    bio: 'Dr. Miriam Kawira specializes in wind farm sitings and regional atmospheric wind shear profiling. Her research utilizes geospatial datasets and meteorological modeling to evaluate wind energy feasibility along the coastal regions of Tanzania and Kenya. She is also a passionate advocate for gender-inclusive STEM training.',
    researchInterests: ['Wind Energy', 'Energy Policy', 'Sustainable Development', 'Climate Change'],
    verified: true,
    followers: [],
    following: 76,
    publicationCount: 19,
    downloads: 940,
    views: 3420,
    citations: 345,
    createdAt: '2025-02-28T16:20:00Z',
    orcid: '0000-0003-2194-0831',
    googleScholar: 'https://scholar.google.com/citations?user=miriam_kawira_nexus',
    linkedin: 'https://linkedin.com/in/miriam-kawira-nm-aist',
    email: 'miriam.kawira@nm-aist.ac.tz',
    website: 'https://nm-aist.ac.tz/staff/miriam-kawira',
    qualifications: ['Ph.D. in Meteorology & Atmospheric Physics (University of Reading)', 'M.Sc. in Environmental Science (UDSM)'],
    experienceYears: 9
  },
  {
    id: 'res-fatima-alao',
    fullName: 'Fatima Alao',
    profilePhoto: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&q=80&w=300&h=300',
    role: 'NGO / Development',
    institution: 'West African Circularity NGO',
    country: 'Ghana',
    bio: 'Fatima Alao is a sustainable development practitioner with a focus on community-led circular economy initiatives. She coordinates international development funding to establish organic-waste bio-fertilizer cooperatives. Her research evaluates the socioeconomic impacts of cleaner cooking solutions and local resource-loop optimization.',
    researchInterests: ['Circular Economy', 'Climate Change', 'Sustainable Development', 'Bioenergy'],
    verified: false,
    followers: [],
    following: 120,
    publicationCount: 11,
    downloads: 510,
    views: 2400,
    citations: 110,
    createdAt: '2025-06-01T10:00:00Z',
    linkedin: 'https://linkedin.com/in/fatima-alao-circularity',
    email: 'f.alao@circular-westafrica.org',
    website: 'https://circular-westafrica.org/team/fatima',
    qualifications: ['M.A. in International Development & Sustainability (University of Ghana)', 'B.A. in Environmental Studies (KNUST)'],
    experienceYears: 7
  }
];

export const SEED_PUBLICATIONS: Publication[] = [
  {
    id: 'pub-adeyemi-solar-microgrids',
    researcherId: 'res-sarah-adeyemi',
    title: 'Hybridizing Solar Photovoltaics with Municipal Solid Waste Biomass: Feasibility Benchmarks for Southwest Nigeria',
    abstract: 'This paper presents a rigorous technoeconomic assessment of hybrid microgrids that combine solar photovoltaic (PV) arrays with small-scale thermochemical waste-to-energy reactors in Southwest Nigeria. By analyzing daily municipal solid waste streams in high-density suburbs, the study outlines optimal sizing methodologies to eliminate intermittent supply constraints while supporting circular resource recovery. Methane output tuning parameters are modeled against local temperature variations to maximize performance and economic yields.',
    category: 'Solar Energy',
    keywords: ['Solar PV', 'Municipal Waste', 'Hybrid Systems', 'Microgrids', 'Nigeria'],
    pdfUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    downloads: 320,
    views: 1120,
    citations: 145,
    createdAt: '2025-02-15T08:00:00Z'
  },
  {
    id: 'pub-adeyemi-lagos-feedstock',
    researcherId: 'res-sarah-adeyemi',
    title: 'Biochemical Characterization of Market Feedstock for Decentralized Anaerobic Co-Digestion',
    abstract: 'Decentralized anaerobic digesters in metropolitan areas often suffer from chemical overloading or organic imbalances. This paper profiles the exact carbohydrate, lipid, and protein ratios of organic refuse collected across four major markets in Lagos. Dynamic co-digestion parameters are simulated to identify optimal carbon-to-nitrogen ratios. Results indicate that co-digesting cassava pulp with vegetable waste increases methane concentration by 28% without requiring premium chemical additives.',
    category: 'Waste-to-Energy',
    keywords: ['Anaerobic Digestion', 'Feedstock', 'Market Waste', 'Methane Yield', 'Lagos'],
    pdfUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    downloads: 410,
    views: 1430,
    citations: 82,
    createdAt: '2025-04-10T10:30:00Z'
  },
  {
    id: 'pub-adeyemi-policy-sovereignty',
    researcherId: 'res-sarah-adeyemi',
    title: 'A Review of Regional Policy Barriers Affecting Decentralized Waste-to-Energy Ingress in ECOWAS',
    abstract: 'Unlocking decentralized waste-to-energy capabilities requires policy frameworks that incentivize smallholder clean-power developers. This study analyzes existing grid codes, licensing restrictions, and feed-in tariffs in West African states. By identifying critical legal hurdles, the paper proposes a simplified regional permitting roadmap to foster rapid private investments into municipal-scale biodigesters.',
    category: 'Energy Policy',
    keywords: ['Energy Policy', 'Waste-to-Energy', 'ECOWAS', 'Grid Codes', 'Licensing'],
    pdfUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    downloads: 180,
    views: 650,
    citations: 34,
    createdAt: '2025-08-01T14:00:00Z'
  },
  {
    id: 'pub-keita-peanut-hulls',
    researcherId: 'res-amadi-keita',
    title: 'Thermochemical Gasification of Peanut Hulls: Empowering Senegal Off-Grid Cooperatives',
    abstract: 'Peanut shells are highly abundant in Senegal but frequently burned as raw biomass, causing localized air pollution. This research optimizes a fixed-bed downdraft gasifier utilizing pelletized peanut hulls. Synthetic gas compositions are quantified under varying oxygen-to-carbon ratios to achieve high calorific value. The paper outlines the practical operational metrics of a 15-kW prototype currently serving an agricultural hub in Kaolack.',
    category: 'Bioenergy',
    keywords: ['Gasification', 'Peanut Hulls', 'Syngas', 'Off-Grid', 'Senegal'],
    pdfUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    downloads: 510,
    views: 1650,
    citations: 210,
    createdAt: '2024-11-12T09:00:00Z'
  },
  {
    id: 'pub-keita-gasification-char',
    researcherId: 'res-amadi-keita',
    title: 'Converting Gasification Char into High-Porosity Agricultural Biochar for Sahel Soils',
    abstract: 'Thermochemical gasification yields byproduct char. This paper evaluates the structural characteristics of agricultural charcoal derived from rice husk and peanut hull gasifiers. Surface area, cation-exchange capacity, and nutrient retention rates are analyzed in tropical Sahel soils. Integrating gasification biochar not only sequesters carbon but also enhances crop water-retention capacity by 35% in sandy terrains.',
    category: 'Circular Economy',
    keywords: ['Biochar', 'Sahel', 'Gasification', 'Carbon Sequestration', 'Soil Health'],
    pdfUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    downloads: 380,
    views: 1100,
    citations: 94,
    createdAt: '2025-03-05T11:15:00Z'
  },
  {
    id: 'pub-demissie-small-hydropower',
    researcherId: 'res-almaz-demissie',
    title: 'Run-of-River Small Hydropower Feasibility Under Climate Intermittency in East African Highlands',
    abstract: 'Small run-of-river installations offer high environmental benefits but are susceptible to seasonal streamflow variations. This research presents hydrologic simulations of two prospective basins in central Ethiopia. By modeling climate change patterns up to 2050, the study evaluates the resilience of turbine selection and recommends robust design flows to prevent dry-season deficits.',
    category: 'Hydropower',
    keywords: ['Hydropower', 'Climate Change', 'Streamflow', 'Ethiopia', 'Hydrology'],
    pdfUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    downloads: 120,
    views: 450,
    citations: 8,
    createdAt: '2025-12-10T10:00:00Z'
  },
  {
    id: 'pub-okafor-battery-storage',
    researcherId: 'res-chinedu-okafor',
    title: 'Productive Use of Mini-Grids: Battery Sizing Optimization for Cold-Storage Chains in Rural Markets',
    abstract: 'Agricultural cold-storage units represent high-demand, inductive loads that stress rural mini-grids. This paper optimizes battery energy storage configuration by correlating temperature limits of agricultural produce with solar generation schedules. Results indicate that thermal-inertia energy storage (pre-cooling during peak solar hours) decreases required chemical battery capacity by 40% while preserving vegetable freshness.',
    category: 'Energy Storage',
    keywords: ['Battery Storage', 'Cold Storage', 'Mini-Grids', 'Load Management', 'Kenya'],
    pdfUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    downloads: 240,
    views: 920,
    citations: 34,
    createdAt: '2025-05-18T13:00:00Z'
  },
  {
    id: 'pub-kawira-wind-shear',
    researcherId: 'res-miriam-kawira',
    title: 'Coastal Wind Shear Profiling along East African Littorals Using Lidar and WRF Models',
    abstract: 'Accurate wind shear calculation is critical to determine optimal hub heights of utility-scale wind turbines. This paper compares Doppler Lidar datasets with Weather Research and Forecasting (WRF) model outputs for coastal Tanzania and Kenya. High-shear wind events are cataloged to evaluate aerodynamic stresses on mechanical rotor configurations, offering high-precision siting recommendations for prospective wind farms.',
    category: 'Wind Energy',
    keywords: ['Wind Shear', 'Doppler Lidar', 'WRF Simulation', 'East Africa', 'Coastal Wind'],
    pdfUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    downloads: 310,
    views: 1040,
    citations: 56,
    createdAt: '2025-04-02T16:00:00Z'
  },
  {
    id: 'pub-alao-cooking-stoves',
    researcherId: 'res-fatima-alao',
    title: 'Socioeconomic Impacts of Solid Fuel Conversion to Biogas Cooking Systems in Rural Cooperatives',
    abstract: 'This paper documents a 12-month field study assessing the shift from wood fuel to domestic bio-digestion systems in Central Ghana. We track fuel-gathering hours, smoke-induced respiratory metrics, and local digestate fertilizer sales. The analysis concludes that community-managed biodigester loops provide a net-positive annual household saving of $310 while reducing carbon output by 4.2 tons per family.',
    category: 'Sustainable Development',
    keywords: ['Biogas Cooking', 'Circularity', 'Socioeconomics', 'Forest Preservation', 'Ghana'],
    pdfUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    downloads: 190,
    views: 810,
    citations: 28,
    createdAt: '2025-07-20T11:00:00Z'
  }
];
